theme: jekyll-theme-minimal
title: Challenge Lab Update
description:  Thank you for visiting but we are hard at work finalizing the Challenge lab!  The Challenge Lab will be ready for your review on Tuesday, october 26th, 2023.  
